version: '3.8'

services:
  mysql:
    build: .
    container_name: mysql-server
    ports:
      - "3306:3306"
    volumes:
      - "//c/Users/kd230/mysql_data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=test@123
    restart: unless-stopped